# Generated by Django 5.0.6 on 2024-07-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, null=True, unique=True, verbose_name='用户名')),
                ('user_mobile', models.CharField(max_length=15, null=True, unique=True, verbose_name='手机号')),
                ('user_pwd', models.CharField(max_length=128, null=True, verbose_name='密码(哈希)')),
            ],
            options={
                'verbose_name': '用户账户信息',
                'verbose_name_plural': '用户账户信息',
                'db_table': 'user_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='新闻标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel', verbose_name='作者')),
            ],
            options={
                'verbose_name': '新闻条目',
                'verbose_name_plural': '新闻条目',
                'db_table': 'news_model',
                'managed': True,
            },
        ),
    ]
