# Generated by Django 5.0.7 on 2024-08-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=20, verbose_name='教室命名')),
                ('roomuse', models.CharField(max_length=50, verbose_name='教室用途')),
                ('roomdesc', models.TextField(blank=True, null=True, verbose_name='教室说明')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='记录修改时间')),
            ],
            options={
                'verbose_name': '教室信息',
                'verbose_name_plural': '教室信息',
                'db_table': 'classroom_info',
                'managed': True,
            },
        ),
    ]
