# Generated by Django 5.0.7 on 2024-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='roomdesc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='教室说明'),
        ),
    ]
