# Generated by Django 5.0.6 on 2024-07-28 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksinfo',
            name='data_createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='数据添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booksinfo',
            name='data_updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='数据修改时间'),
        ),
    ]
