# Generated by Django 5.0.7 on 2024-08-12 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='计算机型号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='零售价格')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存数量')),
                ('detail', models.TextField(verbose_name='产品详情')),
            ],
            options={
                'verbose_name': '计算机库存信息',
                'verbose_name_plural': '计算机库存信息',
                'db_table': 'computer_info',
                'managed': True,
            },
        ),
    ]
