# Generated by Django 5.0.7 on 2024-08-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=10, verbose_name='教师姓名')),
                ('tclass', models.CharField(max_length=10, verbose_name='教授课程')),
                ('tdesc', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'teacher_info',
                'managed': True,
            },
        ),
    ]
