# Generated by Django 5.0.7 on 2024-08-18 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MesCateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('intro', models.CharField(max_length=50, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '留言分类',
                'verbose_name_plural': '留言分类',
                'db_table': 'mescate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='留言标题')),
                ('author', models.CharField(max_length=20, verbose_name='留言人')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('cate', models.ForeignKey(db_column='cate', on_delete=django.db.models.deletion.CASCADE, to='api.mescatemodel', verbose_name='留言类型')),
            ],
            options={
                'verbose_name': '留言内容',
                'verbose_name_plural': '留言内容',
                'db_table': 'messagemodel',
                'managed': True,
            },
        ),
    ]
