# Generated by Django 5.0.6 on 2024-08-02 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('gender', models.CharField(max_length=2, verbose_name='性别')),
                ('hobby', models.CharField(max_length=30, verbose_name='爱好')),
                ('intro', models.TextField(verbose_name='简介')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='留言标题')),
                ('content', models.TextField(max_length=200, verbose_name='留言内容')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('mem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_message.member', verbose_name='发表用户')),
            ],
            options={
                'verbose_name': '留言管理',
                'verbose_name_plural': '留言管理',
                'db_table': 'message',
                'managed': True,
            },
        ),
    ]
