# Generated by Django 5.0.7 on 2024-08-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='任务主题')),
                ('publish', models.CharField(max_length=20, verbose_name='发布人')),
                ('desc', models.TextField(verbose_name='任务详情')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '任务信息',
                'verbose_name_plural': '任务信息',
                'db_table': 'task_model',
                'managed': True,
            },
        ),
    ]
