# Generated by Django 5.0.6 on 2024-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('gender', models.CharField(max_length=1, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('introduce', models.TextField(verbose_name='自我介绍')),
                ('class_name', models.CharField(max_length=5, verbose_name='所属班级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'stu_info',
                'managed': True,
            },
        ),
    ]
