# Generated by Django 5.0.6 on 2024-07-31 11:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20, unique=True, verbose_name='品牌名称')),
                ('brand_info', models.TextField(blank=True, null=True, verbose_name='品牌简介')),
            ],
            options={
                'verbose_name': '品牌信息',
                'verbose_name_plural': '品牌信息',
                'db_table': 'brand_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=20, unique=True, verbose_name='商品名称')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('goods_number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存数量')),
                ('goods_info', models.TextField(blank=True, null=True, verbose_name='商品详情')),
                ('shelf_time', models.DateField(verbose_name='上架时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
                ('goods_brand', models.ForeignKey(db_column='goods_brand', on_delete=django.db.models.deletion.CASCADE, to='goods.brand', verbose_name='所属品牌')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'goods_info',
                'managed': True,
            },
        ),
    ]
