# Generated by Django 5.0.6 on 2024-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='category',
            field=models.CharField(max_length=10, unique=True, verbose_name='类别'),
        ),
    ]
