# Generated by Django 5.0.7 on 2024-08-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '新闻条目',
                'verbose_name_plural': '新闻条目',
                'db_table': 'news_model',
                'managed': True,
            },
        ),
    ]
