# Generated by Django 5.0.7 on 2024-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='工程师姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('professional', models.CharField(max_length=10, verbose_name='专业')),
                ('descinfo', models.CharField(blank=True, max_length=100, null=True, verbose_name='个人简介')),
            ],
            options={
                'verbose_name': '工程师信息',
                'verbose_name_plural': '工程师信息',
                'db_table': 'engineer_info',
                'managed': True,
            },
        ),
    ]
