# Generated by Django 5.0.6 on 2024-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('number', models.IntegerField(verbose_name='商品数量')),
                ('category', models.CharField(max_length=10, unique=True, verbose_name='商品种类')),
            ],
            options={
                'verbose_name': '教学武器商品信息',
                'verbose_name_plural': '教学武器商品信息',
                'db_table': 'goods_info',
                'managed': True,
            },
        ),
    ]
