# Generated by Django 5.0.7 on 2024-08-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部件名称')),
                ('usability', models.CharField(max_length=4, verbose_name='可用性')),
                ('specification', models.CharField(max_length=50, verbose_name='规格')),
                ('createtime', models.DateField(verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '配件信息',
                'verbose_name_plural': '配件信息',
                'db_table': 'electronic_info',
                'managed': True,
            },
        ),
    ]
