# Generated by Django 5.0.6 on 2024-07-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('course', models.CharField(max_length=15, verbose_name='任教科目')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='薪资')),
                ('address', models.TextField(verbose_name='居住地址')),
                ('onboarding_time', models.DateTimeField(verbose_name='入职时间')),
                ('personal_info', models.TextField(null=True, verbose_name='备注信息(选填)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'teachers_info',
                'managed': True,
            },
        ),
    ]
